apiVersion: batch/v1
kind: Job
metadata:
  name: bitcoin-snapshot-loader
  labels:
    app: bitcoin-snapshot-loader
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: bitcoin-snapshot-loader
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: snapshot-loader
          image: bitnami/minideb:bookworm
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              
              echo "Checking for required tools..."
              if ! command -v wget >/dev/null; then
                echo "Installing wget, tar, and lz4..."
                apt-get update -o APT::Sandbox::User=root -y >/dev/null
                apt-get install -o APT::Sandbox::User=root -y wget tar lz4 >/dev/null
              fi

              echo "Clearing /bitcoin/data directory..."
              rm -rf /bitcoin/data/*

              echo "Downloading Bitcoin base snapshot..."
              wget -O /bitcoin/data/bitcoin-base.tar.lz4 https://snapshots.publicnode.com/bitcoin-base.tar.lz4 --progress=bar:force:noscroll

              echo "Downloading Bitcoin part snapshot..."
              wget -O /bitcoin/data/bitcoin-part-921638.tar.lz4 https://snapshots.publicnode.com/bitcoin-part-921638.tar.lz4 --progress=bar:force:noscroll

              echo "Extracting bitcoin-base.tar.lz4..."
              lz4 -d /bitcoin/data/bitcoin-base.tar.lz4 | tar -x -C /bitcoin/data/

              echo "Extracting bitcoin-part-921638.tar.lz4..."
              lz4 -d /bitcoin/data/bitcoin-part-921638.tar.lz4 | tar -x -C /bitcoin/data/

              echo "Cleaning up..."
              rm -f /bitcoin/data/*.lz4

              echo "✅ Snapshot extraction complete!"
          volumeMounts:
            - name: bitcoin-data
              mountPath: /bitcoin/data
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: bitcoin-data-bitcoind-0
