apiVersion: batch/v1
kind: Job
metadata:
  name: bitcoin-snapshot-loader
  labels:
    app: bitcoin-snapshot-loader
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: bitcoin-snapshot-loader
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: snapshot-loader
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              echo "Updating apt and installing required tools..."
              apt-get update -y >/dev/null
              DEBIAN_FRONTEND=noninteractive apt-get install -y wget tar lz4 build-essential >/dev/null

              echo "Clearing /bitcoin/data directory..."
              rm -rf /bitcoin/data/*

              echo "Starting parallel downloads and multi-threaded extraction..."

              # Stream bitcoin-base in background
              (
                echo "[Thread 1] Downloading and extracting bitcoin-base.tar.lz4..."
                wget -qO- https://snapshots.publicnode.com/bitcoin-base.tar.lz4 \
                  | lz4 -d --threads=3 \
                  | tar -x -C /bitcoin/data/ --checkpoint=.5000 --checkpoint-action=echo="[Thread 1] Extracted 5000 files"
                echo "[Thread 1] Done."
              ) &

              # Stream bitcoin-part in background
              (
                echo "[Thread 2] Downloading and extracting bitcoin-part-921638.tar.lz4..."
                wget -qO- https://snapshots.publicnode.com/bitcoin-part-921638.tar.lz4 \
                  | lz4 -d --threads=3 \
                  | tar -x -C /bitcoin/data/ --checkpoint=.5000 --checkpoint-action=echo="[Thread 2] Extracted 5000 files"
                echo "[Thread 2] Done."
              ) &

              # Wait for both to finish
              wait

              echo "Fixing permissions to UID:GID 1000:1000..."
              chown -R 1000:1000 /bitcoin/data

              echo "✅ All snapshots downloaded and extracted in parallel!"
          resources:
            requests:
              cpu: "3"
              memory: "8Gi"
            limits:
              cpu: "3"
              memory: "8Gi"
          volumeMounts:
            - name: bitcoin-data
              mountPath: /bitcoin/data
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: bitcoin-data-bitcoind-0
