apiVersion: batch/v1
kind: Job
metadata:
  name: bitcoin-snapshot-loader
  labels:
    app: bitcoin-snapshot-loader
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600  # Job auto-deletes after 1 hour
  template:
    metadata:
      labels:
        app: bitcoin-snapshot-loader
    spec:
      restartPolicy: Never
      # Run as root to install required tools
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: snapshot-loader
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              echo "Installing required tools (wget, tar, lz4)..."
              apt-get update -y >/dev/null
              DEBIAN_FRONTEND=noninteractive apt-get install -y wget tar lz4 >/dev/null

              echo "Clearing /bitcoin/data directory..."
              rm -rf /bitcoin/data/*

              echo "Starting streamed extraction of bitcoin-base.tar.lz4..."
              wget -qO- https://snapshots.publicnode.com/bitcoin-base.tar.lz4 \
                | lz4 -d | tar -x -C /bitcoin/data/ --checkpoint=.1000 --checkpoint-action=echo="Extracted 1000 files"

              echo "Base snapshot extraction completed."

              echo "Starting streamed extraction of bitcoin-part-921638.tar.lz4..."
              wget -qO- https://snapshots.publicnode.com/bitcoin-part-921638.tar.lz4 \
                | lz4 -d | tar -x -C /bitcoin/data/ --checkpoint=.1000 --checkpoint-action=echo="Extracted 1000 files"

              echo "Part snapshot extraction completed."

              echo "Fixing permissions to UID:GID 1000:1000..."
              chown -R 1000:1000 /bitcoin/data

              echo "✅ Bitcoin snapshot extraction complete!"
          volumeMounts:
            - name: bitcoin-data
              mountPath: /bitcoin/data
      volumes:
        - name: bitcoin-data
          persistentVolumeClaim:
            claimName: bitcoin-data-bitcoind-0
