--- 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitcoin-conf
spec:
  encryptedData:
    rpcpassword: "AgBYiYtJhXkyIujNekiHE/8DJ+OVH1gKXh9yzZPPs2nugOGvQ6cFV1VJihenSDg/NHyfZ+kDm5nFXW3ZrCRj4EMx2dfmMwOJoNdcLuAxuj9FE5uASlX/wobi+g0+fUPDvtzyhPdPGmcGQcVRmJN5zTDCuyPxAFAwYCo/yZSz7q4mjJl7BB8Z7qz1ZHKJIm4VLeFVpGEgfr3FoLN1CGX25Y/+yB6+pbcE2vMQrxFByCwN3REAOnaIJ3vryc9mwPHjIs68C2XwURmX2Se8l6P5UnmsSN6rPBhobiSomXhW01L7UWYrUSnHOOnYxQ9oNg4/NeF1aHbW9NVtUuUrfAAETk7RPJBX/pZIaASVm1Ti2Try11LjzJq5kb7vNrnpt0SKe968TcI8lzOGcLimxjn3lWxcnRS8gXFn7ngeGTpyoMMVHtMChlMCZB6sV1kkGpwrud2x+nPfeNsu77i3au8S0w4s2QRL0HWpzwvixTXXLzSvcGoqcgfawcJY7f1YzHsx21KH86ckz6gFqHjxOOf6YGFb5mbMrLUlkg1DhWGjEBauuEzJCDDxoXf4aVOY3yVNsnKGHaWVtC4+kP9WAkIt5cOZW3QTAdWq1H+JL+lQB2qp3Bc9oMR+kRu9o5REu0RUVnEiDxcwxy+Og5KbWAZAF+1Cmas96qXqnjeHZPleIWtqc5CqlXsW/u/x8E+cOS/LRl5lDPWaLHAHd1JtO2sOargZ0qa2/jwmE1d39w=="
  template:
    metadata:
      name: bitcoin-conf
    data:
      bitcoin.conf: |
        server=1
        txindex=1
        rpcuser=bitcoinrpc
        rpcpassword={{ .rpcpassword }}
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0
        datadir=/bitcoin/data
        blocksonly=1