--- 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitcoin-conf
spec:
  encryptedData:
    rpcpassword: "AgAvgzitK03EV+Oy1E5HGlLMKaRMpNGFIhXFGpihoPflx04ezSDF/F52OjZ88gyQ30QPlTvjA6td10v5V/wm+2my5avirZlptabUqNyPn6NJGdnepxSUaswrjT//zUY6kQqc9Nu5RxKVq2l3L8yixEeaO4l3U4rwyOQ5wfJIAQ9HjWSROVuGf++ryCS39CJMrQP5M/i5SnZ9/3BKgHF8fUnYcGnaucWp4w1bkxYMUs0pqP4NenNRJNdbThQiUoGkX2nyetyD73Iu4PpzrLcqib7O3NqSTNoOniQ/Z8STq17KFFWSbYyFcqyv0DQIygPPqGLQp/f/0cJo8N94IQFtoVC0bmY9bVDyPUomzkaVPMjVhxj7J1lreT4IHaLAtN/A12xggcXRoFZSEtGe64RcEhRERzp+oXTa/KnLHaaLQYRnL/TiAJ1ykPozdVKDL4k0SGcHsPHADNJzwhd4L13/KZWOz4R1fTUL8oToc38kiuh/xsxOB/ohrYSpiiGvtrkCHrGRgt+At+DWQGuxuLJnTDmFMvv3UDmhwyGnkWPoaPEBwlq8IOZe9sjgQP0rewtQv4hTMLPnaTex/xtXdXdnNLSvXYw1fzn4ysbSmFBYWuHTrINzsQix7jxlEDU874CsYxIW39SC53Po4YMgwN9s4mVFYIm+ecnOf7zzcc3nFwnhTxnnpsr7pxccFlnkc2o3wzoxatmfEGVfzJuwGCZSmt7dw7/JFk8aGvvcwg=="
  template:
    metadata:
      name: bitcoin-conf
    data:
      bitcoin.conf: |
        server=1
        txindex=1
        rpcuser=bitcoinrpc
        rpcpassword={{ .rpcpassword }}
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0
        datadir=/bitcoin/data
        blocksonly=1